version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./coldstorage_project:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=coldstorage_project.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
