# Generated by Django 5.2.8 on 2025-11-15 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorageProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g., 'AWS S3', 'Google Cloud Storage')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("nas", "Network Attached Storage"),
                            ("cloud_hot", "Cloud Storage (Hot)"),
                            ("cloud_warm", "Cloud Storage (Warm)"),
                            ("cloud_cold", "Cloud Storage (Cold/Archive)"),
                            ("tape", "Tape Storage"),
                            ("other", "Other"),
                        ],
                        default="cloud_hot",
                        help_text="Type of storage provider",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_gb_monthly",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Monthly cost per GB (e.g., $0.023000)",
                        max_digits=10,
                    ),
                ),
                (
                    "retrieval_cost_per_gb",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cost per GB for data retrieval (e.g., $0.090000)",
                        max_digits=10,
                    ),
                ),
                (
                    "api_cost_per_1000_requests",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cost per 1000 API requests",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Provider description and notes"
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="Provider website URL")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="coldstorage.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (e.g., 'Linux', 'Open Source', 'Media')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of name", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this tag"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Hex color code for UI display (e.g., #FF5733)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional category grouping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="coldstorage.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or title of the data item", max_length=200
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        help_text="Optional subcategory (e.g., 'Indie', 'AAA', 'Documentary')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the item"
                    ),
                ),
                (
                    "examples",
                    models.TextField(
                        blank=True,
                        help_text="Specific examples or instances of this item",
                    ),
                ),
                (
                    "size_estimate_gb",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated storage size in gigabytes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "tags_old",
                    models.CharField(
                        blank=True,
                        help_text="[DEPRECATED] Old comma-separated tags (migrating to tag_set)",
                        max_length=250,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL where this data can be obtained"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes, acquisition status, or special instructions",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Storage priority level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("acquired", "Acquired"),
                            ("stored", "Stored"),
                            ("verified", "Verified"),
                        ],
                        default="planned",
                        help_text="Current acquisition/storage status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Primary category for this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_items",
                        to="coldstorage.category",
                    ),
                ),
                (
                    "tag_set",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for categorization and filtering",
                        related_name="data_items",
                        to="coldstorage.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="StorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded file (optional if tracking external storage)",
                        null=True,
                        upload_to="storage_files/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to file (local or remote)",
                        max_length=500,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        help_text="File size in bytes",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "checksum_md5",
                    models.CharField(
                        blank=True,
                        help_text="MD5 checksum (32 hex chars)",
                        max_length=32,
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum (64 hex chars)",
                        max_length=64,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("nas", "Network Attached Storage"),
                            ("s3", "Amazon S3"),
                            ("glacier", "Amazon Glacier"),
                            ("gcs", "Google Cloud Storage"),
                            ("azure", "Azure Blob Storage"),
                            ("backblaze", "Backblaze B2"),
                            ("other", "Other"),
                        ],
                        default="local",
                        help_text="Where the file is stored",
                        max_length=50,
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        help_text="Full path or URL to the stored file",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("stored", "Stored"),
                            ("verified", "Verified"),
                            ("corrupted", "Corrupted"),
                            ("missing", "Missing"),
                        ],
                        default="pending",
                        help_text="Current file status",
                        max_length=20,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the file was last verified",
                        null=True,
                    ),
                ),
                (
                    "verification_error",
                    models.TextField(
                        blank=True, help_text="Error message if verification failed"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this file"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_item",
                    models.ForeignKey(
                        help_text="Data item this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to="coldstorage.dataitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["data_item", "status"],
                        name="coldstorage_data_it_65901e_idx",
                    ),
                    models.Index(
                        fields=["checksum_sha256"],
                        name="coldstorage_checksu_b0844e_idx",
                    ),
                    models.Index(
                        fields=["storage_location"],
                        name="coldstorage_storage_b8c009_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CostEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_size_gb",
                    models.FloatField(
                        help_text="Estimated storage size in GB",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "monthly_storage_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated monthly storage cost",
                        max_digits=10,
                    ),
                ),
                (
                    "annual_storage_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated annual storage cost",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_retrieval_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated one-time retrieval cost",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_monthly_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual monthly cost (from bills)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_retrieval_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual retrieval cost (from bills)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bandwidth_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bandwidth/egress costs",
                        max_digits=10,
                    ),
                ),
                (
                    "api_request_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="API request costs",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this estimate is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this cost estimate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_item",
                    models.ForeignKey(
                        help_text="Data item this cost estimate is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_estimates",
                        to="coldstorage.dataitem",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Storage provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_estimates",
                        to="coldstorage.storageprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["data_item", "provider"],
                        name="coldstorage_data_it_40b0d4_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="coldstorage_is_acti_77bf78_idx"
                    ),
                ],
                "unique_together": {("data_item", "provider")},
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="coldstorage_name_4288b3_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="coldstorage_slug_f6dad2_idx"),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(
                fields=["category", "subcategory"],
                name="coldstorage_categor_928441_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(
                fields=["status", "priority"], name="coldstorage_status_941f57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(
                fields=["size_estimate_gb"], name="coldstorage_size_es_c20776_idx"
            ),
        ),
    ]
