# Generated by Django 5.2.8 on 2025-11-15 23:08

from django.db import migrations
from django.utils.text import slugify


def migrate_tags_forward(apps, schema_editor):
    """
    Convert comma-separated tags from tags_old field to Tag objects
    and link them via M2M relationship.
    """
    DataItem = apps.get_model('coldstorage', 'DataItem')
    Tag = apps.get_model('coldstorage', 'Tag')

    # Track tags we've created
    tag_cache = {}

    for item in DataItem.objects.all():
        if item.tags_old:
            # Split tags and clean them
            tag_names = [tag.strip() for tag in item.tags_old.split(',') if tag.strip()]

            for tag_name in tag_names:
                # Get or create Tag object
                if tag_name not in tag_cache:
                    slug = slugify(tag_name)

                    # Check if tag exists
                    try:
                        tag = Tag.objects.get(slug=slug)
                    except Tag.DoesNotExist:
                        # Create new tag
                        tag = Tag.objects.create(
                            name=tag_name,
                            slug=slug,
                            color='#6c757d'  # Default color
                        )

                    tag_cache[tag_name] = tag
                else:
                    tag = tag_cache[tag_name]

                # Add tag to item's M2M relationship
                item.tag_set.add(tag)


def migrate_tags_backward(apps, schema_editor):
    """
    Convert Tag objects back to comma-separated tags in tags_old field.
    This is for migration rollback.
    """
    DataItem = apps.get_model('coldstorage', 'DataItem')

    for item in DataItem.objects.all():
        tags = item.tag_set.all()
        if tags:
            tag_names = [tag.name for tag in tags]
            item.tags_old = ', '.join(tag_names)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("coldstorage", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_tags_forward, migrate_tags_backward),
    ]
