# Generated by Django 5.2.8 on 2025-11-15 23:08

from django.db import migrations, transaction
from django.db.utils import IntegrityError
from django.utils.text import slugify


DEFAULT_TAG_COLOR = '#6c757d'


def _unique_slug(Tag, base_slug, max_length):
    """
    Return a free slug, deriving deterministic '-2', '-3', ... suffixes when the
    preferred one is already taken.
    """
    slug = base_slug[:max_length]
    suffix = 2
    while Tag.objects.filter(slug=slug).exists():
        marker = '-%d' % suffix
        slug = '%s%s' % (base_slug[:max_length - len(marker)], marker)
        suffix += 1
    return slug


def _resolve_tag(Tag, name):
    """
    Find, or create, the Tag for one legacy tag name.

    Tag.name and Tag.slug are *both* unique and different names can slugify to
    the same value ('Sci-Fi' and 'Sci Fi' -> 'sci-fi'), so looking up by slug
    and creating on DoesNotExist can collide on the unique name and blow up with
    an IntegrityError. Resolve by name first, then by slug, and only then create
    - under a de-duplicated slug if necessary.
    """
    name_max = Tag._meta.get_field('name').max_length
    slug_max = Tag._meta.get_field('slug').max_length
    name = name[:name_max]

    # 1. Exact name match. This is also what makes a re-run a no-op.
    tag = Tag.objects.filter(name=name).first()
    if tag is not None:
        return tag

    base_slug = slugify(name)[:slug_max] or 'tag'

    # 2. A tag that legitimately owns this slug (its own name slugifies to it)
    #    absorbs the variant spelling - the behaviour this migration always
    #    intended for 'Sci-Fi' vs 'Sci Fi'.
    existing = Tag.objects.filter(slug=base_slug).first()
    if existing is not None and slugify(existing.name)[:slug_max] == base_slug:
        return existing

    # 3. Otherwise create a new tag under a free, deterministic slug (the slug
    #    may be held by a row whose slug was hand-assigned; do not steal it).
    slug = _unique_slug(Tag, base_slug, slug_max)
    try:
        with transaction.atomic():
            return Tag.objects.create(
                name=name,
                slug=slug,
                color=DEFAULT_TAG_COLOR,
            )
    except IntegrityError:
        # Lost a race, or an unexpected collision: fall back to a lookup rather
        # than aborting the whole migration.
        tag = (Tag.objects.filter(name=name).first()
               or Tag.objects.filter(slug=slug).first())
        if tag is None:
            raise
        return tag


def migrate_tags_forward(apps, schema_editor):
    """
    Convert comma-separated tags from tags_old field to Tag objects
    and link them via M2M relationship.

    Safe to re-run: tags are resolved by name/slug before being created and
    M2M add() is idempotent.
    """
    DataItem = apps.get_model('coldstorage', 'DataItem')
    Tag = apps.get_model('coldstorage', 'Tag')

    # Track tags we've resolved, keyed by the raw legacy name.
    tag_cache = {}

    for item in DataItem.objects.all():
        if not item.tags_old:
            continue

        # Split tags and clean them
        tag_names = [tag.strip() for tag in item.tags_old.split(',') if tag.strip()]

        for tag_name in tag_names:
            tag = tag_cache.get(tag_name)
            if tag is None:
                tag = _resolve_tag(Tag, tag_name)
                tag_cache[tag_name] = tag

            # Add tag to item's M2M relationship
            item.tag_set.add(tag)


def migrate_tags_backward(apps, schema_editor):
    """
    Convert Tag objects back to comma-separated tags in the tags_old field.
    This is for migration rollback.
    """
    DataItem = apps.get_model('coldstorage', 'DataItem')
    max_length = DataItem._meta.get_field('tags_old').max_length

    for item in DataItem.objects.all():
        tag_names = list(
            item.tag_set.order_by('name').values_list('name', flat=True)
        )
        if not tag_names:
            continue

        joined = ', '.join(tag_names)
        if max_length and len(joined) > max_length:
            # Keep as many whole names as fit rather than writing a value the
            # column cannot hold.
            joined = ''
            for tag_name in tag_names:
                candidate = tag_name if not joined else '%s, %s' % (joined, tag_name)
                if len(candidate) > max_length:
                    break
                joined = candidate
            if not joined:
                joined = tag_names[0][:max_length]

        item.tags_old = joined
        item.save(update_fields=['tags_old'])


class Migration(migrations.Migration):

    dependencies = [
        ("coldstorage", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_tags_forward, migrate_tags_backward),
    ]
